services:
  postgres:
    image: postgres:15-alpine

  redpanda:
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr=internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr=internal://0.0.0.0:8082
      - --advertise-pandaproxy-addr=internal://redpanda:8082
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster info -X brokers=127.0.0.1:9092 >/dev/null 2>&1"]
      interval: 10s
      timeout: 10s
      retries: 20

  registry-api:
    environment:
      APP_ALLOWED_ORIGINS: "*"
      GATEWAY_PUBLIC_BASE_URL: https://verify.diplomverify.ru
      GATEWAY_SERVICE_TOKEN: diasoft-service-token

  gateway-api:
    environment:
      HTTP_ALLOWED_ORIGINS: "*"
      AUTH_JWT_SECRET: diasoft-team1-demo-secret
      REGISTRY_INTERNAL_BASE_URL: http://registry-api:8080
      REGISTRY_SERVICE_TOKEN: diasoft-service-token

  web:
    environment:
      VITE_AUTH_ENABLED: "false"
      VITE_GATEWAY_BASE_URL: https://verify.diplomverify.ru
      VITE_REGISTRY_BASE_URL: https://registry.diplomverify.ru
      VITE_OIDC_AUTHORITY: https://auth.diplomverify.ru/realms/diasoft
      VITE_OIDC_REDIRECT_URI: https://web.diplomverify.ru/
      VITE_OIDC_POST_LOGOUT_REDIRECT_URI: https://web.diplomverify.ru/
