apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team2
  namespace: argocd
spec:
  description: Team 2 isolated project for one-server multi-tenant deployment.
  sourceRepos:
    - https://gitlab.com/ozzus/platform-infra.git
  destinations:
    - namespace: team2-*
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
