api:
  image:
    repository: registry.gitlab.example.com/team1/diasoft-gateway/gateway-api
    tag: latest
  ingress:
    enabled: true
    host: verify.dev.team1.example.com
    tls:
      enabled: true
      secretName: team1-dev-verify-tls

consumer:
  image:
    repository: registry.gitlab.example.com/team1/diasoft-gateway/gateway-consumer
    tag: latest

replayer:
  image:
    repository: registry.gitlab.example.com/team1/diasoft-gateway/gateway-dlq-replayer
    tag: latest

env:
  HTTP_ALLOWED_ORIGINS: https://web.dev.team1.example.com
  HTTP_TRUSTED_PROXIES: 10.42.0.0/16,10.43.0.0/16,127.0.0.1/32
  KAFKA_SASL_ENABLED: "false"
  KAFKA_TLS_ENABLED: "false"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo.monitoring.svc.cluster.local:4317

externalSecret:
  enabled: false
  targetName: team1-gateway-dev-secrets

deploymentMetadata:
  team: team1
  environment: dev
  imageTag: latest
  registryContractVersion: latest
