replicas: 1
mode: dev

admin:
  existingSecret: team1-keycloak-dev-secrets

ingress:
  enabled: true
  host: auth.dev.diplomverify.ru
  tls:
    enabled: true
    secretName: team1-dev-auth-tls

realm:
  name: diasoft-team1
  frontendClientId: diasoft-web-team1
  redirectUris:
    - https://web.dev.diplomverify.ru/*
    - https://web.diplomverify.ru/*
  postLogoutRedirectUris:
    - https://web.dev.diplomverify.ru/*
    - https://web.diplomverify.ru/*
  bootstrapUsers:
    - username: super_admin
      email: super-admin@diplomverify.ru
      firstName: Team
      lastName: One
      passwordSecretKey: password
      roles:
        - super_admin

externalSecret:
  enabled: false
  targetName: team1-keycloak-dev-secrets

deploymentMetadata:
  team: team1
  environment: dev
