{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: diasoft-gateway-api
spec:
  podSelector:
    matchLabels:
      app: diasoft-gateway-api
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: {{ .Values.networkPolicy.apiIngressPort }}
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        {{- range .Values.networkPolicy.egressPorts }}
        - protocol: TCP
          port: {{ . }}
        {{- end }}
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: UDP
          port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: diasoft-gateway-workers
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - diasoft-gateway-consumer
          - diasoft-gateway-dlq-replayer
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        {{- range .Values.networkPolicy.egressPorts }}
        - protocol: TCP
          port: {{ . }}
        {{- end }}
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: UDP
          port: 53
{{- end }}
