apiVersion: v1
kind: Service
metadata:
  name: diasoft-gateway-api
spec:
  selector:
    app: diasoft-gateway-api
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: diasoft-gateway-consumer
spec:
  selector:
    app: diasoft-gateway-consumer
  ports:
    - name: http
      port: {{ .Values.consumer.service.metricsPort }}
      targetPort: {{ .Values.consumer.service.metricsPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: diasoft-gateway-dlq-replayer
spec:
  selector:
    app: diasoft-gateway-dlq-replayer
  ports:
    - name: http
      port: {{ .Values.replayer.service.metricsPort }}
      targetPort: {{ .Values.replayer.service.metricsPort }}
