image:
  repository: registry.gitlab.com/ozzus/diasoft-registry/registry-api
  tag: latest

ingress:
  enabled: true
  host: registry.dev.edu-proof.ru
  tls:
    enabled: true
    secretName: team2-dev-registry-tls

env:
  OBJECT_STORAGE_ENDPOINT: http://minio.team2-dev-data.svc.cluster.local:9000
  OBJECT_STORAGE_BUCKET: team2-dev-diploma-imports
  OBJECT_STORAGE_REGION: ru-central1
  OIDC_ISSUER_URI: https://auth.dev.edu-proof.ru/realms/diasoft-team2
  APP_ALLOWED_ORIGINS: "*"
  KAFKA_SECURITY_PROTOCOL: PLAINTEXT
  OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo.monitoring.svc.cluster.local:4317

externalSecret:
  enabled: false
  targetName: team2-registry-dev-secrets

deploymentMetadata:
  team: team2
  environment: dev
  imageTag: latest
  contractVersion: latest
