replicas: 1
mode: dev

admin:
  existingSecret: team2-keycloak-dev-secrets

ingress:
  enabled: true
  host: auth.dev.edu-proof.ru
  tls:
    enabled: true
    secretName: team2-dev-auth-tls

realm:
  name: diasoft-team2
  frontendClientId: diasoft-web-team2
  redirectUris:
    - https://web.dev.edu-proof.ru/*
    - https://web.edu-proof.ru/*
  postLogoutRedirectUris:
    - https://web.dev.edu-proof.ru/*
    - https://web.edu-proof.ru/*
  bootstrapUsers:
    - username: super_admin
      email: super-admin@edu-proof.ru
      firstName: Team
      lastName: Two
      passwordSecretKey: password
      roles:
        - super_admin

externalSecret:
  enabled: false
  targetName: team2-keycloak-dev-secrets

deploymentMetadata:
  team: team2
  environment: dev
