mode: production
replicas: 2
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
ingress:
  enabled: true
  host: auth.stage.example.com
  tls:
    enabled: true
    secretName: auth-stage-tls
realm:
  redirectUris:
    - https://web.stage.example.com/*
  postLogoutRedirectUris:
    - https://web.stage.example.com/*
  bootstrapUsers:
    - username: super_admin
      enabled: true
      emailVerified: true
      credentials:
        - type: password
          value: ChangeMe123!
          temporary: false
      realmRoles:
        - super_admin
    - username: university_operator_itmo
      enabled: true
      emailVerified: true
      attributes:
        university_id:
          - "11111111-1111-1111-1111-111111111111"
      credentials:
        - type: password
          value: ChangeMe123!
          temporary: false
      realmRoles:
        - university_operator
    - username: student_001
      enabled: true
      emailVerified: true
      attributes:
        student_external_id:
          - student-001
      credentials:
        - type: password
          value: ChangeMe123!
          temporary: false
      realmRoles:
        - student
externalSecret:
  targetName: keycloak-stage-secrets
  data:
    - secretKey: username
      remoteRef:
        key: keycloak-admin-stage
        property: username
    - secretKey: password
      remoteRef:
        key: keycloak-admin-stage
        property: password
    - secretKey: db_host
      remoteRef:
        key: keycloak-stage
        property: db_host
    - secretKey: db_port
      remoteRef:
        key: keycloak-stage
        property: db_port
    - secretKey: db_username
      remoteRef:
        key: keycloak-stage
        property: db_username
    - secretKey: db_password
      remoteRef:
        key: keycloak-stage
        property: db_password
