image:
  repository: registry.gitlab.com/ozzus/diasoft-web/diasoft-web
  tag: stable

runtimeConfig:
  VITE_AUTH_ENABLED: "true"
  VITE_OIDC_AUTHORITY: https://auth.edu-proof.ru/realms/diasoft-team2
  VITE_OIDC_CLIENT_ID: diasoft-web-team2
  VITE_OIDC_REDIRECT_URI: https://web.edu-proof.ru/
  VITE_OIDC_POST_LOGOUT_REDIRECT_URI: https://web.edu-proof.ru/
  VITE_GATEWAY_BASE_URL: https://verify.edu-proof.ru
  VITE_REGISTRY_BASE_URL: https://registry.edu-proof.ru

ingress:
  enabled: true
  host: web.edu-proof.ru
  tls:
    enabled: true
    secretName: team2-prod-web-tls

deploymentMetadata:
  team: team2
  environment: prod
  imageTag: stable
  contractVersion: stable
