grafana:
  enabled: true
  admin:
    existingSecret: grafana-admin
    userKey: username
    passwordKey: password
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
