apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-nonprod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  project: default
  sources:
    - repoURL: oci://cr.yandex/yc-marketplace/yandex-cloud/externaldns/chart
      chart: externaldns
      targetRevision: 0.5.1-b
      helm:
        valueFiles:
          - $values/helm/addons/external-dns/nonprod.yaml
    - repoURL: https://github.com/ozzus/platform-infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
