apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-25"
spec:
  project: default
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 1.3.1
      helm:
        valueFiles:
          - $values/helm/addons/external-secrets/prod.yaml
    - repoURL: https://gitlab.example.com/platform-infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
