apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-single-node
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  project: default
  sources:
    - repoURL: https://kubernetes-sigs.github.io/external-dns
      chart: external-dns
      targetRevision: 1.16.1
      helm:
        valueFiles:
          - $values/helm/addons/external-dns/single-node.yaml
    - repoURL: https://github.com/ozzus/platform-infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
