apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
spec:
  project: default
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: 4.14.0
      helm:
        valueFiles:
          - $values/helm/addons/ingress-nginx/prod.yaml
    - repoURL: https://github.com/ozzus/platform-infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
