apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://gitlab.com/ozzus/platform-infra.git
    targetRevision: main
    path: helm/charts/keycloak
    helm:
      valueFiles:
        - ../../environments/dev/keycloak.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: diasoft-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
