apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: 6.53.0
      helm:
        valueFiles:
          - $values/helm/addons/loki/prod.yaml
    - repoURL: https://gitlab.com/ozzus/platform-infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
