apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team2-registry-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: team2
  source:
    repoURL: https://github.com/ozzus/platform-infra.git
    targetRevision: main
    path: helm/charts/diasoft-registry
    helm:
      valueFiles:
        - ../../tenants/team2/prod/diasoft-registry.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: team2-prod-app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
