apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team1-keycloak-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: team1
  source:
    repoURL: https://github.com/ozzus/platform-infra.git
    targetRevision: main
    path: helm/charts/keycloak
    helm:
      valueFiles:
        - ../../tenants/team1/prod/keycloak.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: team1-prod-auth
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
