apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team2-web-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: team2
  source:
    repoURL: https://github.com/ozzus/platform-infra.git
    targetRevision: main
    path: helm/charts/diasoft-web
    helm:
      valueFiles:
        - ../../tenants/team2/dev/diasoft-web.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: team2-dev-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
