apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo-nonprod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: tempo-distributed
      targetRevision: 1.58.1
      helm:
        valueFiles:
          - $values/helm/addons/tempo/nonprod.yaml
    - repoURL: https://github.com/ozzus/platform-infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
