apiVersion: v1
kind: ConfigMap
metadata:
  name: diasoft-web-runtime-config
data:
  runtime-config.js: |
    window.__DIASOFT_ENV__ = {
    {{- range $key, $value := .Values.runtimeConfig }}
      {{ $key | quote }}: {{ $value | quote }},
    {{- end }}
    };
