apiVersion: apps/v1
kind: Deployment
metadata:
  name: diasoft-web
spec:
  replicas: {{ .Values.autoscaling.minReplicas }}
  selector:
    matchLabels:
      app: diasoft-web
  template:
    metadata:
      labels:
        app: diasoft-web
    spec:
      serviceAccountName: {{ default "diasoft-web" .Values.serviceAccount.name }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: runtime-config
              mountPath: /usr/share/nginx/html/runtime-config.js
              subPath: runtime-config.js
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: {{ .Values.startupProbe.path }}
              port: {{ .Values.service.port }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: runtime-config
          configMap:
            name: diasoft-web-runtime-config
