{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: diasoft-web
spec:
  podSelector:
    matchLabels:
      app: diasoft-web
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: {{ .Values.networkPolicy.allowedIngressPort }}
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        {{- range .Values.networkPolicy.egressPorts }}
        - protocol: TCP
          port: {{ . }}
        {{- end }}
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: UDP
          port: 53
{{- end }}
